### PR TITLE
[FIX] Added link to spotify icon

### PR DESCRIPTION
**Pull request by mstuttgart**
* Spotify linux client not find icon in this theme. I added a link to icon.

### CODE REVIEW

**Comment by raveit65** [comment]
merged https://github.com/mate-desktop/mate-icon-theme-faenza/commit/c2c91dbb556612c1005ff318c19439558f8e9ca5
Thank you

**Comment by mstuttgart** [comment]
@raveit65 why you not want merge?

**Comment by raveit65** [comment]
@mstuttgart it is merged in master, please read my comment and follow link :smile:

**Comment by mstuttgart** [comment]
Oh sorry! I ask because you not use merge button. Thanks!!

**Comment by raveit65** [comment]
We don't like useless merge commit and use 'git merge --ff-only' via command line.

**Pull request closed without merging**
